
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user1
 */
public class Customer extends javax.swing.JFrame {

    /**
     * Creates new form Customer
     */
      public  String id;  
    
    
    public Customer() {
        
        initComponents();  
    }
      
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTexfirstname = new javax.swing.JTextField();
        jTexlastname = new javax.swing.JTextField();
        jTexaddress = new javax.swing.JTextField();
        jTexemail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTexphone = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 48))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 102));
        jLabel2.setText("Last Name:");

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 0, 102));
        jLabel3.setText("Address:");

        jLabel4.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 0, 102));
        jLabel4.setText("Email Address:");

        jTexfirstname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTexfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexfirstnameActionPerformed(evt);
            }
        });
        jTexfirstname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexfirstnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexfirstnameKeyTyped(evt);
            }
        });

        jTexlastname.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTexlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexlastnameActionPerformed(evt);
            }
        });
        jTexlastname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexlastnameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexlastnameKeyTyped(evt);
            }
        });

        jTexaddress.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTexaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexaddressActionPerformed(evt);
            }
        });
        jTexaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexaddressKeyPressed(evt);
            }
        });

        jTexemail.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTexemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexemailActionPerformed(evt);
            }
        });
        jTexemail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexemailKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Phone Number:");

        jTexphone.setFont(new java.awt.Font("Serif", 0, 24)); // NOI18N
        jTexphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexphoneActionPerformed(evt);
            }
        });
        jTexphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTexphoneKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexphoneKeyTyped(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jButton2.setText("Exit");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registration", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 0, 48), new java.awt.Color(0, 51, 153))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 366, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTexemail, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexlastname, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexphone, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexaddress, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(451, 451, 451)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(573, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTexphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTexaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTexemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jTexfirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTexlastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTexfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexfirstnameActionPerformed

    }//GEN-LAST:event_jTexfirstnameActionPerformed

    private void jTexlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexlastnameActionPerformed

    private void jTexemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexemailActionPerformed

    private void jTexaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexaddressActionPerformed
        
    private void jTexphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexphoneActionPerformed
    public  Customer frame;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        frame=new Customer();
        if (JOptionPane.showConfirmDialog(frame,"Confirm if you want to exit","Fast Food",
        JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
        System.exit(0);
}       // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private Menu menu;
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String f_name=jTexfirstname.getText();
        String l_name=jTexlastname.getText();
        String number=jTexphone.getText();
        String address=jTexaddress.getText();
        String email=jTexemail.getText();
  
        
        if (f_name.equals("")){
            JOptionPane.showMessageDialog(null,"FirstName is Mandatory");
        }
        else if (l_name.equals("")){
            JOptionPane.showMessageDialog(null,"LastName is Mandatory");
        }
        else if (number.equals("")){
            JOptionPane.showMessageDialog(null,"PhoneNumber is Mandatory");
        }
        else if (address.equals("")){
            JOptionPane.showMessageDialog(null,"Address is Mandatory");
        }
        else if (email.equals("")){
            JOptionPane.showMessageDialog(null,"Email is Mandatory");
        }
       
        else{
            menu=new Menu();
            if (JOptionPane.showConfirmDialog(frame,"Do you want to change the Info?","Info Confimation",
                JOptionPane.YES_NO_OPTION)!=JOptionPane.YES_NO_OPTION){
                JOptionPane.showMessageDialog(null,"Now You Are resdy to Place Your Order!");
                new Menu().setVisible(true);
            }
        }       
        
        
        
       
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jTexphoneKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexphoneKeyTyped
        // TODO add your handling code here:
        char isNumber= evt.getKeyChar(); 
        if(!(Character.isDigit(isNumber)) ||(isNumber==KeyEvent.VK_BACK_SPACE) ||(isNumber==KeyEvent.VK_DELETE))
            {
                evt.consume();
            }   
    }//GEN-LAST:event_jTexphoneKeyTyped

    private void jTexfirstnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexfirstnameKeyTyped
        // TODO add your handling code here:
        char isAlphabet=evt.getKeyChar();
        if (!(Character.isLetter(isAlphabet)) || (isAlphabet==KeyEvent.VK_BACK_SPACE) || (isAlphabet==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTexfirstnameKeyTyped

    private void jTexlastnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexlastnameKeyTyped
        // TODO add your handling code here:
        char isAlphabet=evt.getKeyChar();
        if (!(Character.isLetter(isAlphabet)) || (isAlphabet==KeyEvent.VK_BACK_SPACE) || (isAlphabet==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_jTexlastnameKeyTyped

    private void jTexfirstnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexfirstnameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key==10){
            jTexlastname.requestFocus();  
        }
    }//GEN-LAST:event_jTexfirstnameKeyPressed

    private void jTexlastnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexlastnameKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key==10){
            jTexphone.requestFocus();  
        }
    }//GEN-LAST:event_jTexlastnameKeyPressed

    private void jTexphoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexphoneKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key==10){
            jTexaddress.requestFocus();  
        }
    }//GEN-LAST:event_jTexphoneKeyPressed

    private void jTexaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexaddressKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key==10){
            jTexemail.requestFocus();  
        }
    }//GEN-LAST:event_jTexaddressKeyPressed

    private void jTexemailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexemailKeyPressed
        // TODO add your handling code here:
        int key = evt.getKeyCode();
        if (key==10){
            jTexfirstname.requestFocus();  
        }
    }//GEN-LAST:event_jTexemailKeyPressed
    
    
     
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       Customer customer=new Customer();
        
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Window".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer().setVisible(true);
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JTextField jTexaddress;
    public static javax.swing.JTextField jTexemail;
    public static javax.swing.JTextField jTexfirstname;
    public static javax.swing.JTextField jTexlastname;
    public static javax.swing.JTextField jTexphone;
    // End of variables declaration//GEN-END:variables
}
