
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
//import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user1
 */
public class Menu extends javax.swing.JFrame {

     double Price_Hamburger=300;
     double Price_ZingerBurger=220;
     double Price_VeggiBurger=250;
     double Price_BiefBurger=200;
     double Price_ChickenBurger=150;
     double Price_ChowmeinRoll=150;
     double Price_ChickenTikkaRoll=180;
     double Price_VegetableRoll=100;
     double Price_7up=100;
     double Price_String=120;
     double Price_Marinda=150;
     double Price_ClubSandwich=250;
     double Price_SmashedSandwich=300;
     double Price_ChickenSandwich=150;
     double Price_GrilledSandwich=350;
     double Price_MayoSandwich=180;
     
     double[] itemcost=new double[16];  //ARRAY
     
     double subtotal,tax,delivery_charges;
     double TAX=5.2;
    
                                        
                                        /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hd3 = new javax.swing.JLabel();
        shd7 = new javax.swing.JLabel();
        shd8 = new javax.swing.JLabel();
        shd9 = new javax.swing.JLabel();
        jLabprice14 = new javax.swing.JLabel();
        jLabprice15 = new javax.swing.JLabel();
        jLabprice16 = new javax.swing.JLabel();
        jCh7up = new javax.swing.JCheckBox();
        jChstring = new javax.swing.JCheckBox();
        jChmarinda = new javax.swing.JCheckBox();
        jTex7up = new javax.swing.JTextField();
        jTexstring = new javax.swing.JTextField();
        jTexmarinda = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        hd1 = new javax.swing.JLabel();
        shd1 = new javax.swing.JLabel();
        shd2 = new javax.swing.JLabel();
        shd3 = new javax.swing.JLabel();
        jChhamb = new javax.swing.JCheckBox();
        jChzinger = new javax.swing.JCheckBox();
        jChveggi = new javax.swing.JCheckBox();
        jChbief = new javax.swing.JCheckBox();
        jChchicken = new javax.swing.JCheckBox();
        jLabprice1 = new javax.swing.JLabel();
        jLabprice2 = new javax.swing.JLabel();
        jLabprice3 = new javax.swing.JLabel();
        jLabprice4 = new javax.swing.JLabel();
        jLabprice5 = new javax.swing.JLabel();
        jTexhamb = new javax.swing.JTextField();
        jTexveggi = new javax.swing.JTextField();
        jTexzinger = new javax.swing.JTextField();
        jTexbief = new javax.swing.JTextField();
        jTexchicken = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        hd2 = new javax.swing.JLabel();
        shd4 = new javax.swing.JLabel();
        shd5 = new javax.swing.JLabel();
        shd6 = new javax.swing.JLabel();
        jChchowmein = new javax.swing.JCheckBox();
        jChtikka = new javax.swing.JCheckBox();
        jChvegitable = new javax.swing.JCheckBox();
        jLabprice11 = new javax.swing.JLabel();
        jLabprice12 = new javax.swing.JLabel();
        jLabprice13 = new javax.swing.JLabel();
        jTexchowmein = new javax.swing.JTextField();
        jTextikka = new javax.swing.JTextField();
        jTexvegitable = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        hd4 = new javax.swing.JLabel();
        shd10 = new javax.swing.JLabel();
        shd11 = new javax.swing.JLabel();
        shd12 = new javax.swing.JLabel();
        jChclub = new javax.swing.JCheckBox();
        jChsmashed = new javax.swing.JCheckBox();
        jChcsand = new javax.swing.JCheckBox();
        jChgrilled = new javax.swing.JCheckBox();
        jChmayo = new javax.swing.JCheckBox();
        jLabprice6 = new javax.swing.JLabel();
        jLabprice7 = new javax.swing.JLabel();
        jLabprice8 = new javax.swing.JLabel();
        jLabprice9 = new javax.swing.JLabel();
        jLabprice10 = new javax.swing.JLabel();
        jTexsmashed = new javax.swing.JTextField();
        jTexcsand = new javax.swing.JTextField();
        jTexmayo = new javax.swing.JTextField();
        jTexgrilled = new javax.swing.JTextField();
        jTexclub = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabsubtotal = new javax.swing.JLabel();
        jLabtax = new javax.swing.JLabel();
        jLabTax = new javax.swing.JLabel();
        jLabdelcharge = new javax.swing.JLabel();
        jLabDeliveryCharges = new javax.swing.JLabel();
        jButtotal = new javax.swing.JButton();
        jLabtotal = new javax.swing.JLabel();
        jLabSubtotal = new javax.swing.JLabel();
        jButOkay = new javax.swing.JButton();
        jButreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Online Fast Food Ordering System", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Snap ITC", 1, 48), new java.awt.Color(0, 0, 153))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        hd3.setBackground(new java.awt.Color(255, 255, 255));
        hd3.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        hd3.setForeground(new java.awt.Color(204, 102, 0));
        hd3.setText("Drinks");

        shd7.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd7.setForeground(new java.awt.Color(153, 0, 153));
        shd7.setText("Items");

        shd8.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd8.setForeground(new java.awt.Color(153, 0, 153));
        shd8.setText("Price");

        shd9.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd9.setForeground(new java.awt.Color(153, 0, 153));
        shd9.setText("Quantity");

        jLabprice14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice14.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice14.setText("100");

        jLabprice15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice15.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice15.setText("120");

        jLabprice16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice16.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice16.setText("150");

        jCh7up.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jCh7up.setForeground(new java.awt.Color(0, 102, 204));
        jCh7up.setText("  7up");
        jCh7up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCh7upActionPerformed(evt);
            }
        });

        jChstring.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChstring.setForeground(new java.awt.Color(0, 102, 204));
        jChstring.setText("  String");
        jChstring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChstringActionPerformed(evt);
            }
        });

        jChmarinda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChmarinda.setForeground(new java.awt.Color(0, 102, 204));
        jChmarinda.setText("  Marinda");
        jChmarinda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChmarindaActionPerformed(evt);
            }
        });

        jTex7up.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTex7up.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTex7up.setText("0");
        jTex7up.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTex7upKeyTyped(evt);
            }
        });

        jTexstring.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexstring.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexstring.setText("0");
        jTexstring.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexstringKeyTyped(evt);
            }
        });

        jTexmarinda.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexmarinda.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexmarinda.setText("0");
        jTexmarinda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexmarindaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(hd3, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd7)
                    .addComponent(jCh7up)
                    .addComponent(jChstring)
                    .addComponent(jChmarinda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabprice16)
                            .addComponent(jLabprice14)
                            .addComponent(jLabprice15))))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTexmarinda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jTexstring, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTex7up, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(hd3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shd7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shd8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shd9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabprice14)
                    .addComponent(jCh7up)
                    .addComponent(jTex7up, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jTexstring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChstring)
                            .addComponent(jLabprice15))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jChmarinda)
                        .addComponent(jLabprice16))
                    .addComponent(jTexmarinda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        hd1.setBackground(new java.awt.Color(255, 255, 255));
        hd1.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        hd1.setForeground(new java.awt.Color(204, 102, 0));
        hd1.setText("Burger");

        shd1.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd1.setForeground(new java.awt.Color(153, 0, 153));
        shd1.setText("Items");

        shd2.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd2.setForeground(new java.awt.Color(153, 0, 153));
        shd2.setText("Price");

        shd3.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd3.setForeground(new java.awt.Color(153, 0, 153));
        shd3.setText("Quantity");

        jChhamb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChhamb.setForeground(new java.awt.Color(0, 102, 204));
        jChhamb.setText("   HamBurger");
        jChhamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChhambActionPerformed(evt);
            }
        });

        jChzinger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChzinger.setForeground(new java.awt.Color(0, 102, 204));
        jChzinger.setText("  ZingerBurger");
        jChzinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChzingerActionPerformed(evt);
            }
        });

        jChveggi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChveggi.setForeground(new java.awt.Color(0, 102, 204));
        jChveggi.setText("  Veggi Burger");
        jChveggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChveggiActionPerformed(evt);
            }
        });

        jChbief.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChbief.setForeground(new java.awt.Color(0, 102, 204));
        jChbief.setText("  Bief Burger");
        jChbief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChbiefActionPerformed(evt);
            }
        });

        jChchicken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChchicken.setForeground(new java.awt.Color(0, 102, 204));
        jChchicken.setText("  ChickenBurger");
        jChchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChchickenActionPerformed(evt);
            }
        });

        jLabprice1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice1.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice1.setText("250");

        jLabprice2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice2.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice2.setText("200");

        jLabprice3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice3.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice3.setText("150");

        jLabprice4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice4.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice4.setText("300");

        jLabprice5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice5.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice5.setText("220");

        jTexhamb.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexhamb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexhamb.setText("0");
        jTexhamb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexhambActionPerformed(evt);
            }
        });
        jTexhamb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexhambKeyTyped(evt);
            }
        });

        jTexveggi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexveggi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexveggi.setText("0");
        jTexveggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexveggiActionPerformed(evt);
            }
        });
        jTexveggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexveggiKeyTyped(evt);
            }
        });

        jTexzinger.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexzinger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexzinger.setText("0");
        jTexzinger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexzingerActionPerformed(evt);
            }
        });
        jTexzinger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexzingerKeyTyped(evt);
            }
        });

        jTexbief.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexbief.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexbief.setText("0");
        jTexbief.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexbiefActionPerformed(evt);
            }
        });
        jTexbief.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexbiefKeyTyped(evt);
            }
        });

        jTexchicken.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexchicken.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexchicken.setText("0");
        jTexchicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexchickenActionPerformed(evt);
            }
        });
        jTexchicken.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexchickenKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(hd1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                            .addComponent(shd1)
                                            .addGap(4, 4, 4))
                                        .addComponent(jChzinger))
                                    .addComponent(jChveggi)
                                    .addComponent(jChhamb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(shd2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabprice5)
                                            .addComponent(jLabprice4)
                                            .addComponent(jLabprice1)))))
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jChbief, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabprice2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                    .addComponent(jChchicken)
                                    .addGap(59, 59, 59)
                                    .addComponent(jLabprice3))))
                        .addGap(68, 68, 68)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTexchicken, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shd3)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTexbief, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                                .addComponent(jTexveggi, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTexzinger, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTexhamb, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(hd1)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shd3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(shd2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(shd1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChhamb)
                    .addComponent(jLabprice4)
                    .addComponent(jTexhamb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jChzinger)
                    .addComponent(jLabprice5)
                    .addComponent(jTexzinger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabprice1)
                    .addComponent(jChveggi)
                    .addComponent(jTexveggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTexbief, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jChbief)
                    .addComponent(jLabprice2))
                .addGap(25, 25, 25)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTexchicken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabprice3)
                    .addComponent(jChchicken))
                .addGap(166, 166, 166))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        hd2.setBackground(new java.awt.Color(255, 255, 255));
        hd2.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        hd2.setForeground(new java.awt.Color(204, 102, 0));
        hd2.setText("Roll");

        shd4.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd4.setForeground(new java.awt.Color(153, 0, 153));
        shd4.setText("Quantity");

        shd5.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd5.setForeground(new java.awt.Color(153, 0, 153));
        shd5.setText("Items");

        shd6.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd6.setForeground(new java.awt.Color(153, 0, 153));
        shd6.setText("Price");

        jChchowmein.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChchowmein.setForeground(new java.awt.Color(0, 102, 204));
        jChchowmein.setText(" Chowmein Roll");
        jChchowmein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChchowmeinActionPerformed(evt);
            }
        });

        jChtikka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChtikka.setForeground(new java.awt.Color(0, 102, 204));
        jChtikka.setText(" Chicken Tikka Roll");
        jChtikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChtikkaActionPerformed(evt);
            }
        });

        jChvegitable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChvegitable.setForeground(new java.awt.Color(0, 102, 204));
        jChvegitable.setText("  Vegetable Roll");
        jChvegitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChvegitableActionPerformed(evt);
            }
        });

        jLabprice11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice11.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice11.setText("150");

        jLabprice12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice12.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice12.setText("180");

        jLabprice13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice13.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice13.setText("100");

        jTexchowmein.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexchowmein.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexchowmein.setText("0");
        jTexchowmein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexchowmeinActionPerformed(evt);
            }
        });
        jTexchowmein.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexchowmeinKeyTyped(evt);
            }
        });

        jTextikka.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextikka.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextikka.setText("0");
        jTextikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextikkaActionPerformed(evt);
            }
        });
        jTextikka.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextikkaKeyTyped(evt);
            }
        });

        jTexvegitable.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexvegitable.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexvegitable.setText("0");
        jTexvegitable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexvegitableActionPerformed(evt);
            }
        });
        jTexvegitable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexvegitableKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChvegitable)
                            .addComponent(jChchowmein)
                            .addComponent(jChtikka))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabprice12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabprice11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabprice13, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(48, 48, 48))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(shd5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shd6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTexvegitable, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addComponent(jTextikka, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTexchowmein, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hd2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(hd2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shd4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(shd6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(227, 227, 227))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(shd5, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChchowmein)
                            .addComponent(jLabprice11)
                            .addComponent(jTexchowmein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChtikka)
                            .addComponent(jLabprice12)
                            .addComponent(jTextikka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChvegitable)
                            .addComponent(jLabprice13)
                            .addComponent(jTexvegitable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        hd4.setBackground(new java.awt.Color(255, 255, 255));
        hd4.setFont(new java.awt.Font("Vivaldi", 1, 48)); // NOI18N
        hd4.setForeground(new java.awt.Color(204, 102, 0));
        hd4.setText("Sandwich");

        shd10.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd10.setForeground(new java.awt.Color(153, 0, 153));
        shd10.setText("Items");

        shd11.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd11.setForeground(new java.awt.Color(153, 0, 153));
        shd11.setText("Price");

        shd12.setFont(new java.awt.Font("Script MT Bold", 0, 24)); // NOI18N
        shd12.setForeground(new java.awt.Color(153, 0, 153));
        shd12.setText("Quantity");
        shd12.setToolTipText("");

        jChclub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChclub.setForeground(new java.awt.Color(0, 102, 204));
        jChclub.setText("  Club Sandwich");
        jChclub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChclubActionPerformed(evt);
            }
        });

        jChsmashed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChsmashed.setForeground(new java.awt.Color(0, 102, 204));
        jChsmashed.setText("  Smashed Sandwich");
        jChsmashed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChsmashedActionPerformed(evt);
            }
        });

        jChcsand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChcsand.setForeground(new java.awt.Color(0, 102, 204));
        jChcsand.setText("  Chicken Sandwich");
        jChcsand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChcsandActionPerformed(evt);
            }
        });

        jChgrilled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChgrilled.setForeground(new java.awt.Color(0, 102, 204));
        jChgrilled.setText("  Grilled Sandwich");
        jChgrilled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChgrilledActionPerformed(evt);
            }
        });

        jChmayo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jChmayo.setForeground(new java.awt.Color(0, 102, 204));
        jChmayo.setText("  Mayo Sandwich");
        jChmayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChmayoActionPerformed(evt);
            }
        });

        jLabprice6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice6.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice6.setText("250");

        jLabprice7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice7.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice7.setText("300");

        jLabprice8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice8.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice8.setText("150");

        jLabprice9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice9.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice9.setText("350");

        jLabprice10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabprice10.setForeground(new java.awt.Color(0, 102, 153));
        jLabprice10.setText("180");

        jTexsmashed.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexsmashed.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexsmashed.setText("0");
        jTexsmashed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexsmashedKeyTyped(evt);
            }
        });

        jTexcsand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexcsand.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexcsand.setText("0");
        jTexcsand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexcsandKeyTyped(evt);
            }
        });

        jTexmayo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexmayo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexmayo.setText("0");
        jTexmayo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexmayoKeyTyped(evt);
            }
        });

        jTexgrilled.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexgrilled.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexgrilled.setText("0");
        jTexgrilled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexgrilledKeyTyped(evt);
            }
        });

        jTexclub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTexclub.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTexclub.setText("0");
        jTexclub.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTexclubKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(hd4, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd10)
                    .addComponent(jChclub)
                    .addComponent(jChsmashed)
                    .addComponent(jChcsand)
                    .addComponent(jChgrilled)
                    .addComponent(jChmayo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(shd11, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabprice6)
                            .addComponent(jLabprice8)
                            .addComponent(jLabprice7)
                            .addComponent(jLabprice9)
                            .addComponent(jLabprice10))))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(shd12))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTexclub, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                            .addComponent(jTexsmashed)
                            .addComponent(jTexcsand)
                            .addComponent(jTexgrilled)
                            .addComponent(jTexmayo))))
                .addGap(54, 54, 54))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(hd4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shd10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shd11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jChclub)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jChsmashed)
                                    .addComponent(jLabprice7)
                                    .addComponent(jTexsmashed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabprice6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jChcsand)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabprice8)
                                    .addComponent(jTexcsand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChgrilled)
                            .addComponent(jLabprice9)
                            .addComponent(jTexgrilled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jChmayo)
                            .addComponent(jLabprice10)
                            .addComponent(jTexmayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(195, 195, 195))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(shd12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTexclub, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jLabsubtotal.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabsubtotal.setForeground(new java.awt.Color(102, 0, 153));
        jLabsubtotal.setText("Subtotal");
        jLabsubtotal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabtax.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabtax.setForeground(new java.awt.Color(102, 0, 153));
        jLabtax.setText("   Tax");
        jLabtax.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabTax.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabTax.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabdelcharge.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jLabdelcharge.setForeground(new java.awt.Color(102, 0, 153));
        jLabdelcharge.setText("Delivery Charges");
        jLabdelcharge.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabDeliveryCharges.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabDeliveryCharges.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabDeliveryCharges.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtotal.setBackground(new java.awt.Color(204, 204, 204));
        jButtotal.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jButtotal.setForeground(new java.awt.Color(102, 0, 153));
        jButtotal.setText("Total ");
        jButtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtotalActionPerformed(evt);
            }
        });

        jLabtotal.setBackground(new java.awt.Color(153, 153, 153));
        jLabtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabSubtotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabSubtotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabdelcharge)
                    .addComponent(jLabtax, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabTax, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabDeliveryCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabTax, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabDeliveryCharges, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabsubtotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabtax, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabdelcharge, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButOkay.setBackground(new java.awt.Color(204, 204, 204));
        jButOkay.setFont(new java.awt.Font("Script MT Bold", 1, 18)); // NOI18N
        jButOkay.setForeground(new java.awt.Color(153, 0, 153));
        jButOkay.setText("Done");
        jButOkay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButOkayActionPerformed(evt);
            }
        });

        jButreset.setBackground(new java.awt.Color(204, 204, 204));
        jButreset.setFont(new java.awt.Font("Script MT Bold", 1, 24)); // NOI18N
        jButreset.setForeground(new java.awt.Color(102, 0, 153));
        jButreset.setText("Reset");
        jButreset.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jButreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(117, 117, 117))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(343, 343, 343)
                        .addComponent(jButreset, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(281, 281, 281)
                        .addComponent(jButOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButreset, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(969, 969, 969))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jChhambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChhambActionPerformed
       // TODO add your handling code here:
       if(jChhamb.isSelected())
       {
           jTexhamb.setEnabled(true);
           jTexhamb.requestFocus();
           jTexhamb.setText("");
       }
       else
       {
           jTexhamb.setEnabled(false);
           jTexhamb.setText("0");
       }
        
       
    }//GEN-LAST:event_jChhambActionPerformed

    private void jChchowmeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChchowmeinActionPerformed
        // TODO add your handling code here:
        if(jChchowmein.isSelected())
       {
           jTexchowmein.setEnabled(true);
           jTexchowmein.requestFocus();
           jTexchowmein.setText("");
       }
       else
       {
           jTexchowmein.setEnabled(false);
           jTexchowmein.setText("0");
       }
        
    }//GEN-LAST:event_jChchowmeinActionPerformed

    private void jCh7upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCh7upActionPerformed
        // TODO add your handling code here:
        if(jCh7up.isSelected())
       {
           jTex7up.setEnabled(true);
           jTex7up.requestFocus();
           jTex7up.setText("");
       }
       else
       {
           jTex7up.setEnabled(false);
           jTex7up.setText("0");
       }
    }//GEN-LAST:event_jCh7upActionPerformed

    private void jTexhambKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexhambKeyTyped
 char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }// TODO add your handling code here:
    }//GEN-LAST:event_jTexhambKeyTyped

    private void jTexhambActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexhambActionPerformed


// TODO add your handling code here:
    }//GEN-LAST:event_jTexhambActionPerformed

    private void jTexzingerKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexzingerKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexzingerKeyTyped

    private void jTexveggiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexveggiKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexveggiKeyTyped

    private void jTexbiefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexbiefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexbiefActionPerformed

    private void jTexbiefKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexbiefKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexbiefKeyTyped

    private void jTexchickenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexchickenKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexchickenKeyTyped

    private void jTextikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextikkaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextikkaActionPerformed

    private void jTexchowmeinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexchowmeinKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexchowmeinKeyTyped

    private void jTextikkaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextikkaKeyTyped
  char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }       // TODO add your handling code here:
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextikkaKeyTyped

    private void jTexvegitableKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexvegitableKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTexvegitableKeyTyped

    private void jTexstringKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexstringKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTexstringKeyTyped

    private void jTexmarindaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexmarindaKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexmarindaKeyTyped

    private void jTexclubKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexclubKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexclubKeyTyped

    private void jTexsmashedKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexsmashedKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexsmashedKeyTyped

    private void jTexgrilledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexgrilledKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexgrilledKeyTyped

    private void jTexmayoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexmayoKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTexmayoKeyTyped

    private void jTexchowmeinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexchowmeinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexchowmeinActionPerformed

    private void jTex7upKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTex7upKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTex7upKeyTyped

    private void jTexcsandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTexcsandKeyTyped
char isNumber= evt.getKeyChar(); 
 if(!(Character.isDigit(isNumber))
||(isNumber==KeyEvent.VK_BACK_SPACE)
||(isNumber==KeyEvent.VK_DELETE))
        {
        evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTexcsandKeyTyped

    private void jButtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtotalActionPerformed
        // TODO add your handling code here:
 
        itemcost[0]=Price_Hamburger*Double.parseDouble(jTexhamb.getText());
        itemcost[1]=Price_ZingerBurger*Double.parseDouble(jTexzinger.getText());
        itemcost[2]=Price_VeggiBurger*Double.parseDouble(jTexveggi.getText());
        itemcost[3]=Price_BiefBurger*Double.parseDouble(jTexbief.getText());
        itemcost[4]=Price_ChickenBurger*Double.parseDouble(jTexchicken.getText());
        itemcost[5]=Price_ChowmeinRoll*Double.parseDouble(jTexchowmein.getText());
        itemcost[6]=Price_ChickenTikkaRoll*Double.parseDouble(jTextikka.getText());
        itemcost[7]=Price_VegetableRoll*Double.parseDouble(jTexvegitable.getText());
        itemcost[8]=Price_7up*Double.parseDouble(jTex7up.getText());
        itemcost[9]=Price_String*Double.parseDouble(jTexstring.getText());
        itemcost[10]=Price_Marinda*Double.parseDouble(jTexmarinda.getText());
        itemcost[11]=Price_ClubSandwich*Double.parseDouble(jTexclub.getText());
        itemcost[12]=Price_SmashedSandwich*Double.parseDouble(jTexsmashed.getText());
        itemcost[13]=Price_ChickenSandwich*Double.parseDouble(jTexcsand.getText());
        itemcost[14]=Price_GrilledSandwich*Double.parseDouble(jTexgrilled.getText());
        itemcost[15]=Price_MayoSandwich*Double.parseDouble(jTexmayo.getText());
        
        
       
        subtotal=itemcost[0]+itemcost[1]+itemcost[2]+itemcost[3]+itemcost[4]+itemcost[5]+itemcost[6]
                +itemcost[7]+itemcost[8]+itemcost[9]+itemcost[10]+itemcost[11]+itemcost[12]+
                itemcost[13]+itemcost[14]+itemcost[15];
        
        tax= (subtotal*TAX)/100;
        if (subtotal<=500)
        {
            delivery_charges=50;
        }
        else if (subtotal<=1000)
        {
            delivery_charges=100;
        }
        else
        {
            delivery_charges=150;
        }
        
        jLabSubtotal.setText(String.valueOf(subtotal));   //Subtotal
        jLabTax.setText(String.valueOf(tax));        //Tax
        jLabDeliveryCharges.setText(String.valueOf(delivery_charges)); //Delivery Charges
        
        jLabtotal.setText(String.valueOf(subtotal+tax+delivery_charges));  //Total
        
        
        
        
   
      
        
    }//GEN-LAST:event_jButtotalActionPerformed

    private void jChzingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChzingerActionPerformed
        // TODO add your handling code here:
        if(jChzinger.isSelected())
       {
           jTexzinger.setEnabled(true);
           jTexzinger.requestFocus();
           jTexzinger.setText("");
       }
       else
       {
           jTexzinger.setEnabled(false);
           jTexzinger.setText("0");
       }
        
    }//GEN-LAST:event_jChzingerActionPerformed

    private void jChveggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChveggiActionPerformed
        // TODO add your handling code here:
        if(jChveggi.isSelected())
       {
           jTexveggi.setEnabled(true);
           jTexveggi.requestFocus();
           jTexveggi.setText("");
       }
       else
       {
           jTexveggi.setEnabled(false);
           jTexveggi.setText("0");
       }
    }//GEN-LAST:event_jChveggiActionPerformed

    private void jTexveggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexveggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexveggiActionPerformed

    private void jTexvegitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexvegitableActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexvegitableActionPerformed

    private void jTexchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexchickenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexchickenActionPerformed

    private void jChmarindaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChmarindaActionPerformed
        // TODO add your handling code here:
         if(jChmarinda.isSelected())
       {
           jTexmarinda.setEnabled(true);
           jTexmarinda.requestFocus();
           jTexmarinda.setText("");
       }
       else
       {
           jTexmarinda.setEnabled(false);
           jTexmarinda.setText("0");
       }
        
    }//GEN-LAST:event_jChmarindaActionPerformed

    private void jTexzingerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexzingerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexzingerActionPerformed

    private void jChbiefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChbiefActionPerformed
        // TODO add your handling code here:
        if(jChbief.isSelected())
       {
           jTexbief.setEnabled(true);
           jTexbief.requestFocus();
           jTexbief.setText("");
       }
       else
       {
           jTexbief.setEnabled(false);
           jTexbief.setText("0");
       }
    }//GEN-LAST:event_jChbiefActionPerformed

    private void jChchickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChchickenActionPerformed
        // TODO add your handling code here:
         if(jChchicken.isSelected())
       {
           jTexchicken.setEnabled(true);
           jTexchicken.requestFocus();
           jTexchicken.setText("");
       }
       else
       {
           jTexchicken.setEnabled(false);
           jTexchicken.setText("0");
       }

    }//GEN-LAST:event_jChchickenActionPerformed

    private void jChtikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChtikkaActionPerformed
        // TODO add your handling code here:
         if(jChtikka.isSelected())
       {
           jTextikka.setEnabled(true);
           jTextikka.requestFocus();
           jTextikka.setText("");
       }
       else
       {
           jTextikka.setEnabled(false);
           jTextikka.setText("0");
       }
    }//GEN-LAST:event_jChtikkaActionPerformed

    private void jChvegitableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChvegitableActionPerformed
        // TODO add your handling code here:
        if(jChvegitable.isSelected())
       {
           jTexvegitable.setEnabled(true);
           jTexvegitable.requestFocus();
           jTexvegitable.setText("");
       }
       else
       {
           jTexvegitable.setEnabled(false);
           jTexvegitable.setText("0");
       }
    }//GEN-LAST:event_jChvegitableActionPerformed

    private void jChstringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChstringActionPerformed
        // TODO add your handling code here:
        if(jChstring.isSelected())
       {
           jTexstring.setEnabled(true);
           jTexstring.requestFocus();
           jTexstring.setText("");
       }
       else
       {
           jTexstring.setEnabled(false);
           jTexstring.setText("0");
       }
    }//GEN-LAST:event_jChstringActionPerformed

    private void jChclubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChclubActionPerformed
        // TODO add your handling code here:
        if(jChclub.isSelected())
       {
           jTexclub.setEnabled(true);
           jTexclub.requestFocus();
           jTexclub.setText("");
       }
       else
       {
           jTexclub.setEnabled(false);
           jTexclub.setText("0");
       }
        
    }//GEN-LAST:event_jChclubActionPerformed

    private void jChsmashedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChsmashedActionPerformed
        // TODO add your handling code here:
        if(jChsmashed.isSelected())
       {
           jTexsmashed.setEnabled(true);
           jTexsmashed.requestFocus();
           jTexsmashed.setText("");
       }
       else
       {
           jTexsmashed.setEnabled(false);
           jTexsmashed.setText("0");
       }
    }//GEN-LAST:event_jChsmashedActionPerformed

    private void jChcsandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChcsandActionPerformed
        // TODO add your handling code here:
        if(jChcsand.isSelected())
       {
           jTexcsand.setEnabled(true);
           jTexcsand.requestFocus();
           jTexcsand.setText("");
       }
       else
       {
           jTexcsand.setEnabled(false);
           jTexcsand.setText("0");
       }
        
    }//GEN-LAST:event_jChcsandActionPerformed

    private void jChgrilledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChgrilledActionPerformed
        // TODO add your handling code here:
          if(jChgrilled.isSelected())
       {
           jTexgrilled.setEnabled(true);
           jTexgrilled.requestFocus();
           jTexgrilled.setText("");
       }
       else
       {
           jTexgrilled.setEnabled(false);
           jTexgrilled.setText("0");
       }
          
    }//GEN-LAST:event_jChgrilledActionPerformed

    private void jChmayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChmayoActionPerformed
        // TODO add your handling code here:
        if(jChmayo.isSelected())
        {
           jTexmayo.setEnabled(true);
           jTexmayo.requestFocus();
           jTexmayo.setText("");
        }
       else
        {
           jTexmayo.setEnabled(false);
           jTexmayo.setText("0");
        }
    }//GEN-LAST:event_jChmayoActionPerformed
    
    private OrderReceive frame;
    
    
    
    private void jButOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButOkayActionPerformed
        // TODO add your handling code here:
            
            String total=jLabtotal.getText();
            
            if (total.equals("")){
            JOptionPane.showMessageDialog(null,"You must check your Amount Brfore Ordering by clicking on Total");
            }
            else {
                frame=new OrderReceive();
                if (JOptionPane.showConfirmDialog(frame,"Is your order confirm?","Order Confimation",
                JOptionPane.YES_NO_OPTION)==JOptionPane.YES_NO_OPTION){
                new OrderReceive().setVisible(true);
                
            }
       
           
        
           
       }
       
    }//GEN-LAST:event_jButOkayActionPerformed

    private void jButresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButresetActionPerformed
        // TODO add your handling code here:
        jTexhamb.setText("0");
        jTexveggi.setText("0");
        jTexzinger.setText("0");
        jTexbief.setText("0");
        jTexchicken.setText("0");
        jTexsmashed.setText("0");
        jTexcsand.setText("0");
        jTexmayo.setText("0");
        jTexgrilled.setText("0");
        jTexclub.setText("0");
        jTexchowmein.setText("0");
        jTextikka.setText("0");
        jTexvegitable.setText("0");
        jTex7up.setText("0");
        jTexstring.setText("0");
        jTexmarinda.setText("0");
        
        //Total button reset
        jLabSubtotal.setText("");
        jLabTax.setText("");
        jLabDeliveryCharges.setText("");
        jLabtotal.setText("");
        
        jChhamb.setSelected(false);
        jChzinger.setSelected(false);
        jChveggi.setSelected(false);
        jChbief.setSelected(false);
        jChchicken.setSelected(false);
        jChchowmein.setSelected(false);
        jChtikka.setSelected(false);
        jChvegitable.setSelected(false);
        jChclub.setSelected(false);
        jChsmashed.setSelected(false);
        jChcsand.setSelected(false);
        jChgrilled.setSelected(false);
        jChmayo.setSelected(false);
        jCh7up.setSelected(false);
        jChstring.setSelected(false);
        jChmarinda.setSelected(false);
        
       jButtotal.setSelected(false);
        
        
        
    }//GEN-LAST:event_jButresetActionPerformed
    Customer c;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Menu menu =new Menu();
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);  
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hd1;
    private javax.swing.JLabel hd2;
    private javax.swing.JLabel hd3;
    private javax.swing.JLabel hd4;
    private javax.swing.JButton jButOkay;
    private javax.swing.JButton jButreset;
    private javax.swing.JButton jButtotal;
    private javax.swing.JCheckBox jCh7up;
    private javax.swing.JCheckBox jChbief;
    private javax.swing.JCheckBox jChchicken;
    private javax.swing.JCheckBox jChchowmein;
    private javax.swing.JCheckBox jChclub;
    private javax.swing.JCheckBox jChcsand;
    private javax.swing.JCheckBox jChgrilled;
    private javax.swing.JCheckBox jChhamb;
    private javax.swing.JCheckBox jChmarinda;
    private javax.swing.JCheckBox jChmayo;
    private javax.swing.JCheckBox jChsmashed;
    private javax.swing.JCheckBox jChstring;
    private javax.swing.JCheckBox jChtikka;
    private javax.swing.JCheckBox jChveggi;
    private javax.swing.JCheckBox jChvegitable;
    private javax.swing.JCheckBox jChzinger;
    public static javax.swing.JLabel jLabDeliveryCharges;
    private javax.swing.JLabel jLabSubtotal;
    public static javax.swing.JLabel jLabTax;
    private javax.swing.JLabel jLabdelcharge;
    private javax.swing.JLabel jLabprice1;
    private javax.swing.JLabel jLabprice10;
    private javax.swing.JLabel jLabprice11;
    private javax.swing.JLabel jLabprice12;
    private javax.swing.JLabel jLabprice13;
    private javax.swing.JLabel jLabprice14;
    private javax.swing.JLabel jLabprice15;
    private javax.swing.JLabel jLabprice16;
    private javax.swing.JLabel jLabprice2;
    private javax.swing.JLabel jLabprice3;
    private javax.swing.JLabel jLabprice4;
    private javax.swing.JLabel jLabprice5;
    private javax.swing.JLabel jLabprice6;
    private javax.swing.JLabel jLabprice7;
    private javax.swing.JLabel jLabprice8;
    private javax.swing.JLabel jLabprice9;
    private javax.swing.JLabel jLabsubtotal;
    private javax.swing.JLabel jLabtax;
    public static javax.swing.JLabel jLabtotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTex7up;
    private javax.swing.JTextField jTexbief;
    private javax.swing.JTextField jTexchicken;
    private javax.swing.JTextField jTexchowmein;
    private javax.swing.JTextField jTexclub;
    private javax.swing.JTextField jTexcsand;
    private javax.swing.JTextField jTexgrilled;
    private javax.swing.JTextField jTexhamb;
    private javax.swing.JTextField jTexmarinda;
    private javax.swing.JTextField jTexmayo;
    private javax.swing.JTextField jTexsmashed;
    private javax.swing.JTextField jTexstring;
    private javax.swing.JTextField jTextikka;
    private javax.swing.JTextField jTexveggi;
    private javax.swing.JTextField jTexvegitable;
    private javax.swing.JTextField jTexzinger;
    private javax.swing.JLabel shd1;
    private javax.swing.JLabel shd10;
    private javax.swing.JLabel shd11;
    private javax.swing.JLabel shd12;
    private javax.swing.JLabel shd2;
    private javax.swing.JLabel shd3;
    private javax.swing.JLabel shd4;
    private javax.swing.JLabel shd5;
    private javax.swing.JLabel shd6;
    private javax.swing.JLabel shd7;
    private javax.swing.JLabel shd8;
    private javax.swing.JLabel shd9;
    // End of variables declaration//GEN-END:variables
}
