/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Pcw1
 */
public class OrderReceive extends javax.swing.JFrame {

  
   
     
    
    public OrderReceive() {
        initComponents();
      
        jLabfname.setText("Customer Name:      "+ Customer.jTexfirstname.getText());
        jLablname.setText("Last Name:              "+Customer.jTexlastname.getText());
       jLabadress.setText("Phone Number:        "+Customer.jTexphone.getText());
      jLabpnumber.setText("Adress:                    "+Customer.jTexaddress.getText());
        jLabemail.setText("Email Adress:           "+Customer.jTexemail.getText());
            jLabT.setText("Tax Charges:            "+Menu.jLabTax.getText());
            jLabD.setText("Delivery Charges:     "+Menu.jLabDeliveryCharges.getText());
           jLabT2.setText("Total Amount:          "+Menu.jLabtotal.getText());
            
             
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLablname = new javax.swing.JLabel();
        jLabadress = new javax.swing.JLabel();
        jLabpnumber = new javax.swing.JLabel();
        jLabemail = new javax.swing.JLabel();
        jPanOrderReceipt = new javax.swing.JPanel();
        jLabT = new javax.swing.JLabel();
        jLabD = new javax.swing.JLabel();
        jLabT2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabfname = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLablname.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLablname.setText("lname");

        jLabadress.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabadress.setText("phone");

        jLabpnumber.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabpnumber.setText("address");

        jLabemail.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabemail.setText("email");

        jPanOrderReceipt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Receipt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Script MT Bold", 1, 48), new java.awt.Color(153, 0, 153))); // NOI18N

        javax.swing.GroupLayout jPanOrderReceiptLayout = new javax.swing.GroupLayout(jPanOrderReceipt);
        jPanOrderReceipt.setLayout(jPanOrderReceiptLayout);
        jPanOrderReceiptLayout.setHorizontalGroup(
            jPanOrderReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 326, Short.MAX_VALUE)
        );
        jPanOrderReceiptLayout.setVerticalGroup(
            jPanOrderReceiptLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabT.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabT.setText("Tax charges");

        jLabD.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabD.setText("Delivery Charges");

        jLabT2.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabT2.setText("Total Amount");

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\user1\\OneDrive\\Pictures\\Capture net1.PNG")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\user1\\OneDrive\\Pictures\\Capture.png")); // NOI18N

        jLabfname.setFont(new java.awt.Font("Lucida Calligraphy", 0, 18)); // NOI18N
        jLabfname.setText("fname");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabpnumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabadress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLablname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabT2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabfname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanOrderReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)))
                .addComponent(jLabel5)
                .addContainerGap(337, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jPanOrderReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(jLabfname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLablname)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabadress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabpnumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabT)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabD)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabT2))
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabD;
    private javax.swing.JLabel jLabT;
    private javax.swing.JLabel jLabT2;
    private javax.swing.JLabel jLabadress;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabemail;
    private javax.swing.JLabel jLabfname;
    private javax.swing.JLabel jLablname;
    private javax.swing.JLabel jLabpnumber;
    private javax.swing.JPanel jPanOrderReceipt;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
